// <auto-generated />
namespace EDDNBodyDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SplitSectors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SplitSectors));
        
        string IMigrationMetadata.Id
        {
            get { return "201809150711091_SplitSectors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
